version: "3.9"

services:
  cachewarmer:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./config.local.yaml:/app/config.local.yaml:ro
      - ./credentials:/app/credentials:ro
    ports:
      - "3001:3001"
